#!/usr/bin/env bash
mkdir -p ~/.ssh
# Ensures the .ssh directory exists for the ubuntu user

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7fakeKeyExampleOnly== userisaac" >> ~/.ssh/authorized_keys
# Adds the given public key to the authorized_keys file

chmod 700 ~/.ssh
# Sets secure permissions for the .ssh directory

chmod 600 ~/.ssh/authorized_keys
# Sets secure permissions for the authorized_keys file


