#!/usr/bin/env bash
# This script configures HAProxy for SSL termination on port 443 using Certbot certificates

cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # SSL tuning
    tune.ssl.default-dh-param 2048

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend https-in
    bind *:443 ssl crt /etc/ssl/private/www.mydomain.com.pem
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 <WEB_01_IP>:80 check
    server web-02 <WEB_02_IP>:80 check
    server lb-01  <WEB_03_IP>:80 check
EOF
