#!/usr/bin/env bash

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create the redirection configuration inside the default server block
sed -i '/location \/ {/a \\n    location /redirect_me {\n        return 301 https://www.yahoo.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart nginx using 'service' (not systemctl)
service nginx restart

# Make it executable
chmod +x 3-redirection

#Run It
./3-redirection
